### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [tonyf/uroom-web#1]
Hi @tonyf,

I would like to introduce my project which is -almost- same thing with your project. The project name is [Mağara](https://github.com/BerkhanBerkdemir/magara#readme).

Also, here is the [reason](https://github.com/BerkhanBerkdemir/magara/wiki/Frequently-Asked-Questions#why-did-you-build-an-application-for-students) for building this application.

I'm looking a contributor who can implement some cool feature.

I saw this awesome project which you had done everything yourself. Therefore, I wrote this ~issue~ (it is not exactly an issue).

**Comment by jimacoff** [comment]
awesome  project but  the listing  does not have index.
user can  only create a list but user can not   see the listing create by  landlord

**Comment by BerkhanBerkdemir** [comment]
I'm sorry @jimacoff. I didn't understand that. Could you explain a bit?

**Comment by tonyf** [comment]
Hey guys, I'm no longer actively maintaining this and am busy with other projects.

**Comment by jimacoff** [comment]
for thsi project two different user are allow to register,
As landlord
or Regular user
but when regular user register he suppose to see all the listing of the landlord, but the listing is not show to regular user for him to book for the house.
please help me out for this issue

**Comment by jimacoff** [comment]
> Hey guys, I'm no longer actively maintaining this and am busy with other projects.

@tonyf  please this project highly intresting and well helfull to me, help us out to solve this issue

**Comment by tonyf** [comment]
I'm pretty sure anyone can see all the listings view the search_controller. Don't recall being able to view listings as ever being an issue. It's been more than 2 years since I last worked on this but I believe everything was in a working state. The only work left was to redo the UI.

**Comment by jimacoff** [comment]
> I'm pretty sure anyone can see all the listings view the search_controller. Don't recall being able to view listings as ever being an issue. It's been more than 2 years since I last worked on this but I believe everything was in a working state. The only work left was to redo the UI.

thank you for your reply.
this project was branches with master,chat,airbnb, new-design and design, but search function, message function and house listing for user to view does not show in the main master branches.
